### ISSUE TITLE
Consol log

### ISSUE THREAD

**Issue by Szkalownik** [antaresproject/core#3]
Hi, 

I think it should not be any console log here
![ss 2017-02-15 at 01 52 53](https://cloud.githubusercontent.com/assets/25772035/22975294/815424a8-f386-11e6-82e0-d279d5bf8272.png)

 
.

**Comment by mountstone** [comment]
This issue should not be reported here. 
Please go to [antares-frontend](https://github.com/antaresproject/antares-front-end) repository.
