### ISSUE TITLE
unable to scroll dialog with install details

### ISSUE THREAD

**Issue by mountstone** [antaresproject/core#8]

**Comment by MarcinKozak** [comment]
@mountstone Fixed in 6db4f90291b568d4f2a390927c295ff0d5abbfc8

**Comment by mountstone** [comment]
@MarcinKozak Removing auto scroll won't resolve the problem.  Auto scroll should work as default and when user is scrolling up it cannot glitch whole content. Take a look on travis.org when building process is started. It should work the same...

**Comment by MarcinKozak** [comment]
@mountstone Preventing auto scroll will happen only when the content of the console will not stick to the bottom of window.

**Comment by mountstone** [comment]
@MarcinKozak not working on 4 step of app installation

**Comment by MarcinKozak** [comment]
@mountstone fixed by disabling perfect scrollbar module for the preview console.

**Comment by mountstone** [comment]
@MarcinKozak still not working properly

![2](https://cloud.githubusercontent.com/assets/6020063/25992420/be71199a-3706-11e7-92f1-da8ee8faca87.gif)

**Comment by MarcinKozak** [comment]
@mountstone fixed in a2cf08dbd576afc664d04db8ed4378c1ac8eb8a1
